### ISSUE TITLE
The "with" property in a job's step doesn't allow numbers/booleans

### ISSUE THREAD

**Issue by jrparish** [ArmaanT/cdkactions#7]
This appears to be a type issue where the "with" field only accepts a StringMap when numbers/booleans are also acceptable.

Input:
![image](https://user-images.githubusercontent.com/5173987/104225438-01b65780-540c-11eb-9738-d6a9ef486f4d.png)

Result:
![image](https://user-images.githubusercontent.com/5173987/104225522-1db9f900-540c-11eb-8d4f-542002d71aec.png)

Additional use case for boolean:
![image](https://user-images.githubusercontent.com/5173987/104229260-a4bda000-5411-11eb-9583-2bc6fbde456c.png)

**Comment by ArmaanT** [comment]
Nice catch! Looks like the official docs only had examples with string values. I just cut a release that allows for number and boolean values. Thanks!
